name: IaC Security Scan

on:
  workflow_call:

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.tar.gz
          tar -xzf trivy_0.49.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Trivy IaC Scan
        run: |
          trivy config --severity CRITICAL,HIGH --exit-code 1 .

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: iac-report
          path: trivy-results